name: Test Python

on:
  push:
    paths:
      - 'Python/**'
      - '.github/workflows/Python.yml'
  pull_request:
    paths:
      - 'Python/**'
      - '.github/workflows/Python.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up dependencies
      working-directory: Python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test
      working-directory: Python
      run: python -m nose

    - name: Report using branch name (dynamic, use for a pair on each branch)
      run: |
        export GIT_BRANCH_NAME=$(git symbolic-ref --short HEAD)
        export GIT_BRANCH_NAME=$( echo "$GIT_BRANCH_NAME" | sed 's/ /%20/g' )
        curl -X GET ${{ secrets.PUSH_COUNTER_URL }}/record/$GIT_BRANCH_NAME?build=green
